# Generated by Django 3.1.3 on 2020-11-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=20, primary_key='true', serialize=False)),
                ('pw', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, default='/profile/default.png', upload_to='profile')),
                ('name', models.CharField(max_length=20)),
                ('msg', models.CharField(blank='true', default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('from_id', models.ManyToManyField(related_name='_account_from_id_+', to='sand1.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, upload_to='post')),
                ('msg', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sand1.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sand1.account')),
                ('post_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sand1.post')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='like_comments',
            field=models.ManyToManyField(related_name='like_user', to='sand1.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='like_posts',
            field=models.ManyToManyField(related_name='like_user', to='sand1.Post'),
        ),
    ]
