# Generated by Django 3.1.3 on 2020-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sand1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.CharField(default='0.jpg', max_length=200),
        ),
    ]
