# Generated by Django 3.1.3 on 2020-11-18 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sand1', '0004_auto_20201118_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='account',
            name='time',
        ),
        migrations.AddField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
