# Generated by Django 3.1.3 on 2020-11-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sand1', '0005_auto_20201118_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
