# Generated by Django 3.1.3 on 2020-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sand1', '0006_auto_20201118_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
